### ISSUE TITLE
add "Related Publications" section 

### ISSUE THREAD

**Issue by christinerogers** [christinerogers/EEGNet#27]
This can be a section on the about page, with a bulleted list so i can copy-paste paper references and links.
Assume spacing/proportions for 5 publications for now (these papers are written by multiple of the PIs listed so let's put them in a separate section, not under any one PI in particular). 

 -- Use the below as placeholder text : 
* Frauscher, B. et al., 2018. Atlas of the normal intracranial electroencephalogram: Neurophysiological awake activity in different cortical areas. Brain.  https://doi.org/10.1093/brain/awy035
* Frauscher B, et al., 2018. High frequency oscillations in the normal human brain. Annals of Neurology.
https://doi.org/10.1002/ana.25304
* von Ellenrieder N, et al., 2019. How the human brain sleeps: Direct cortical recordings from normal human sleep. Annals of Neurology. https://doi.org/10.1002/ana.25651

-- per alan's request, sep.12 
(from emails sep 12-14)

**Comment by 3design** [comment]
see PR#33

**Comment by christinerogers** [comment]
awesommmme. thank you!
