### ISSUE TITLE
add Headshots from PIs

### ISSUE THREAD

**Issue by christinerogers** [christinerogers/EEGNet#37]
are currently trickling in by email, derek has already started adding next to each profile on the About page. 
if we get them all and they all make it online by Monday, that's ideal. 

For those headshots we haven't listed profiles for yet (e.g. Pedro valdes-sosa, James desjardins, stephanie etc) -- could you add them to the repo anyway? 
then i'll add the html and text for their profile when there's a moment. thanks! 

including the full name in the image name would be ideal e.g. team-faranak-farzan.jpg

**Comment by 3design** [comment]
#44 adds Anne G, Stefan v N, Teena W, Faranak F with appropriate html (merged)

**Comment by 3design** [comment]
#45 adds Sarah, Pedro, and Stefanie images with no html

**Comment by christinerogers** [comment]
#45  (autolinking should work when written just as #45)

**Comment by 3design** [comment]
#46 adds Erin White (thanks for the tip!)

**Comment by christinerogers** [comment]
Erin Panda (just clarifying for my/future purposes)

**Comment by 3design** [comment]
#49 updated Isabelle with html

thanks for the clarification!

**Comment by christinerogers** [comment]
still trickling in, not closing this issue yet (e.g. #50)

updating the header to say: if it's easy going forward, let's name future-incoming photos with both first and last names when possible e.g. team-erin-panda.jpg
