### ISSUE TITLE
css tweak: make subtitle printed on the new animation more visible

### ISSUE THREAD

**Issue by christinerogers** [christinerogers/EEGNet#38]
the words "Collaborative EEG platform for advancing neuroscience" are not visible where they're printed over the video animation. 
I'm pretty sure it's a tiny css tweak, when you have a second.
truly not urgent since slim chance anyone will know/remember they're there :)

**Comment by 3design** [comment]
PR#41 should address this (merged)

**Comment by christinerogers** [comment]
resovled by #41 👍
