### ISSUE TITLE
New member: Gavin Winston, Queen's. 

### ISSUE THREAD

**Issue by christinerogers** [christinerogers/EEGNet#60]
Hi derek, no need to pull the trigger on this yet, this is a placeholder ticket until I forward you (when I have them) his photo and bio.  (when i do so i'll try to explicitly link to this issue) 
3 parts to this : 
* add photo for Gavin Winston 
* add his bio (he can go near Brock in the list)  
* add Queen's University as a spot on the map.

**Comment by christinerogers** [comment]
Time to pull the trigger -- Please add @3design this researcher & map pin.

His photo and bio from : https://deptmed.queensu.ca/people/gavin-winston

 any more info needed for this update? don't hesitate and thanks!

**Comment by 3design** [comment]
Bio from site is several paragraphs long while all other bios are limited to opening and single body. Is there a way we can reduce this?

I've reduced his bio to 3 paragraphs that outline his current work, his achievements, and his memberships. Pls let me know if this is ok.

**Comment by christinerogers** [comment]
Sure, great idea. - 

Could you paste it all in, issue a PR ? 
and then I'll edit it down in the GitHub Pr before merging.

**Comment by 3design** [comment]
sorry I already merged an edited version in #67

**Comment by christinerogers** [comment]
no prob, i'll tweak and issue a pr. thanks
