### ISSUE TITLE
Wording tweaks: About page 

### ISSUE THREAD

**Issue by christinerogers** [christinerogers/EEGNet#65]
- I see a "plus" and a  triangle/arrow in everyone's "Click to read more" grey bar

-  Alan's bio para1 : remove the sentence "He has 652... index=192)." (leave everything else)

There will be one more person to add, the kingston/queens guy (in another issue)

**Comment by 3design** [comment]
the arrow comes from -webkit- rendering the < details > element. Used the following solution:

details > summary {
  list-style: none;
}
details > summary::-webkit-details-marker {
  display: none;
}

**Comment by christinerogers** [comment]
LGTM (looks great to me) - thanks Derek
