### ISSUE TITLE
migrate to new repo on aces : eegnet_website 

### ISSUE THREAD

**Issue by christinerogers** [christinerogers/EEGNet#79]

**Comment by christinerogers** [comment]
step 1: 
upload the main branch code from this repo to https://github.com/aces/eegnet_website. --> main branch 

step 2: 
- [ ] turn on Pages in the Settings of that Repo -- pointing to master branch

**Comment by 3design** [comment]
completed. will need to create a 'coming soon' page

**Comment by christinerogers** [comment]
awesome thanks -- closing
